### ISSUE TITLE
git

### ISSUE THREAD

**Issue by dmraji** [piovere/UTK_NE_python#1]
So to clarify - we are recommending git, just not covering it here?

**Comment by piovere** [comment]
Exactly. I really think everyone should learn it, but I was thinking we should limit to stuff students need for the class. (I would hate to do it, but I could also possibly see Jupyter notebook going away for the same reason).

**Comment by piovere** [comment]
Oh, and Anaconda (though it does make things simpler if we're providing installation instructions for python anyway).

**Comment by dmraji** [comment]
Perhaps if we want to limit the focus as much as possible, just work with pip.

Actually, since most people will probably be on win10 or mac, what is the easiest path to get up and running on those systems?

**Comment by piovere** [comment]
Macs come with python 3.7 and 2.7 as of macOS 10.15; for Windows I think you're signing on to a download and install anyway. Anaconda does give you a GUI to start up Jupyter on both of those systems (Linux too I think?) if we think that's of value

**Comment by dmraji** [comment]
In that case, let's plan for conda-centricity. I think for people that this kinda thing is more foreign to, having to go install a bunch of stuff can seem like a bit stumbling block. The less scattered things are the better
